# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-28 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcshenzhous', '0002_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticles',
            name='author',
        ),
        migrations.DeleteModel(
            name='BlogArticles',
        ),
    ]
